### ISSUE TITLE
Cannot smelt to steel and bricks.

### ISSUE THREAD

**Issue by OskarPepryk** [anythingapplied/WhistleStop#1]
When I put iron plates or stone in big smelters, they don't do anything. I tried that both on modded and vanilla game.

**Comment by OskarPepryk** [comment]
The problem is that required ingredients don't fit in input slots of the furnace (100 stone or 250 iron). And there cannot be more than 1 input slot in the furnace.

**Comment by anythingapplied** [comment]
Looks like a furnace just can't take more than an item's stacksize, and I don't see a direct way to get around that, but have come up with a couple workarounds:

- I can increase the stacksize of iron and stone
- I can change the entity type of the big furnace to an assembling machine entity type.

I think the second option is better as it doesn't affect other gameplay and would provide better support for mods.

This also means that you'll have to pick a recipe like you do with assembling machines, but that isn't much of a side-effect.  Thanks for the report, you can expect a fix in the next day or two.

**Comment by anythingapplied** [comment]
The issue has now been fixed in version 0.0.2 by changing the type to an assembly machine
